name: Build and Deploy Code
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        run: echo "Hello World"
      - uses: actions/checkout@v2
      - name: say hello Hamza
        run: echo "Hello Hamza"
